# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.2.1/rest-clients.json
RestClients:
  IDP-Document-Capturing-API:
    UUID: c316f4d1-daa6-4ca2-b3e0-68133e54eb99
    Url: ${ivy.var.idpUtils.apiProxyUrl}
    Icon: res:/webContent/icons/BlueFilesIcon.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - org.glassfish.jersey.media.multipart.MultiPartFeature
    - com.axonivy.utils.idp.auth.IDPAuthFeature
    Properties:
      AUTH.apiKey: ${ivy.var.idpUtils.apiKeySecret}
      JSON.Deserialization.FAIL_ON_UNKNOWN_PROPERTIES: 'false'
      JSON.Deserialization.FAIL_ON_INVALID_SUBTYPE: 'false'
      JSON.Deserialization.FAIL_ON_IGNORED_PROPERTIES: 'false'
    OpenAPI:
      Namespace: com.axonivy.utils.idp.model
      ResolveFully: true
