/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Standardized name of business transaction.
 */
public enum BusinessTransactionType {
  ANFORDERUNG_ANGEBOT("Anforderung-Angebot"),
  ANFORDERUNG_UNTERLAGEN("Anforderung-Unterlagen"),
  ANFRAGE("Anfrage"),
  ANGEBOT("Angebot"),
  ANSCHRIFT_NAME("Anschrift-Name"),
  ANTRAG_2_VP("Antrag-2-VP"),
  ANTRAG_GESAMT("Antrag-Gesamt"),
  ANTRAGSERGAENZUNG("Antragsergaenzung"),
  ARZTBERICHT("Arztbericht"),
  AUSKUNFT("Auskunft"),
  AUSZAHLUNG("Auszahlung"),
  BEFUNDE("Befunde"),
  BEITRAGSFREI("Beitragsfrei"),
  BEZUGSRECHT("Bezugsrecht"),
  CREDITREFORM("Creditreform"),
  DYNAMIKWIDERSPRUCH("Dynamikwiderspruch"),
  EINGANGSPOST_LEISTUNG("Eingangspost-Leistung"),
  FINANZAMTBESCHEINIGUNG("Finanzamtbescheinigung"),
  GWG_NACHWEIS("GWG-Nachweis"),
  KOSTEN("Kosten"),
  KUENDIGUNG_VN("Kuendigung-VN"),
  KUENDIGUNG_VORMERK_ABLEHNUNG("Kuendigung-Vormerk-Ablehnung"),
  LIQUIDATION("Liquidation"),
  MELDUNG_TOD("Meldung-Tod"),
  NACHWEIS_EINKOMMEN_DARLEHEN("Nachweis-Einkommen-Darlehen"),
  RV_VOTUM_ABLAGE("RV-Votum-Ablage"),
  SEPA_MANDAT("SEPA-Mandat"),
  SCHRIFTWECHSEL("Schriftwechsel"),
  STERBEURKUNDE("Sterbeurkunde"),
  URKUNDE("Urkunde"),
  VN_WECHSEL("VN-Wechsel"),
  VERFUEGUNG("Verfuegung"),
  VERFUEGUNG_FREIGABE("Verfuegung-Freigabe"),
  VERLUSTERKLAERUNG("Verlusterklaerung"),
  VORPRUEFUNG("Vorpruefung"),
  VOTUM("Votum"),
  WIDERRUF("Widerruf"),
  ZAHLUNGSVERKEHR("Zahlungsverkehr"),
  ZUSATZVEREINBARUNG("Zusatzvereinbarung"),
  RECHTLICHE_KORRESPONDENZ("Rechtliche-Korrespondenz"),
  TECHNISCHE_AENDERUNG("Technische-Aenderung");

  private String value;

  BusinessTransactionType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BusinessTransactionType fromValue(String input) {
    for (BusinessTransactionType b : BusinessTransactionType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
