/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DataAccessSchemasCorrespondenceCorrespondenceV1DocCategory {
  OFFER("offer"),
  NOTIFICATION("notification"),
  NOTICE("notice"),
  FINE("fine"),
  CREDIT_NOTE("credit_note"),
  TERMINATION("termination"),
  LEGAL("legal"),
  DUNNING_LETTER("dunning_letter"),
  INVOICE("invoice"),
  MISCELLANEOUS("miscellaneous"),
  FINANCE("finance"),
  INVITATION("invitation"),
  ADVERTISEMENT("advertisement"),
  PRIVATE("private");

  private String value;

  DataAccessSchemasCorrespondenceCorrespondenceV1DocCategory(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasCorrespondenceCorrespondenceV1DocCategory fromValue(String input) {
    for (DataAccessSchemasCorrespondenceCorrespondenceV1DocCategory b : DataAccessSchemasCorrespondenceCorrespondenceV1DocCategory.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
