/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DataAccessSchemasIdentityDocIdentityDocV2IdentityDocType {
  ID_CARD("id_card"),
  PASSPORT("passport"),
  DRIVERS_LICENSE("drivers_license"),
  RESIDENCE_PERMIT("residence_permit"),
  PROBATIONARY_PERMIT("probationary_permit"),
  SETTLEMENT_PERMIT("settlement_permit"),
  BLUE_CARD("blue_card"),
  VISA("visa"),
  PROVISIONAL_CERTIFICATE("provisional_certificate"),
  SUPPLEMENTARY_SHEET("supplementary_sheet");

  private String value;

  DataAccessSchemasIdentityDocIdentityDocV2IdentityDocType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasIdentityDocIdentityDocV2IdentityDocType fromValue(String input) {
    for (DataAccessSchemasIdentityDocIdentityDocV2IdentityDocType b : DataAccessSchemasIdentityDocIdentityDocV2IdentityDocType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
