/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DataAccessSchemasLegalDocLegalDocV2LegalDocClasses {
  DZ_A("DZ-A"),
  DZ_A_EINGESCHR_NKT("DZ-A eingeschränkt"),
  DZ_A_G("DZ-A+G"),
  DZ_A_G_EINGESCHR_NKT("DZ-A+G eingeschränkt"),
  DZ_DGN("DZ-DGN"),
  DZ_G("DZ-G"),
  DZ_G_EINGESCHR_NKT("DZ-G eingeschränkt"),
  RSVABLEHNUNG("RSVAblehnung"),
  RSVRUECKFRAGEN("RSVRueckfragen"),
  AZ("AZ"),
  EV("EV"),
  EB("EB"),
  GKR("GKR"),
  URTEIL("Urteil"),
  VT("VT"),
  BESCHLUSS("Beschluss"),
  KOSTENFESTSETZUNG("Kostenfestsetzung"),
  VU("VU"),
  ANSCHREIBEN("Anschreiben"),
  DZ_KLAGEERWEITERUNG("DZ-Klageerweiterung"),
  GKR_EINZAHLUNG("GKR_Einzahlung"),
  GT("GT"),
  KEW("KEW"),
  VEA("VEA");

  private String value;

  DataAccessSchemasLegalDocLegalDocV2LegalDocClasses(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasLegalDocLegalDocV2LegalDocClasses fromValue(String input) {
    for (DataAccessSchemasLegalDocLegalDocV2LegalDocClasses b : DataAccessSchemasLegalDocLegalDocV2LegalDocClasses.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
