/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DataAccessSchemasOtherOtherV1DocCategory {
  ANFRAGE("anfrage"),
  ANGEBOT("angebot"),
  BENACHRICHTIGUNG("benachrichtigung"),
  BESCHEID("bescheid"),
  BESTELLBESTAETIGUNG("bestellbestaetigung"),
  BUSSGELD("bussgeld"),
  EINLADUNG("einladung"),
  GUTSCHRIFT("gutschrift"),
  KONTO("konto"),
  KUENDIGUNG("kuendigung"),
  MAHNUNG("mahnung"),
  PERSOENLICH("persoenlich"),
  RECHNUNG("rechnung"),
  VERTRAG("vertrag"),
  WERBUNG("werbung"),
  SONSTIGES("sonstiges");

  private String value;

  DataAccessSchemasOtherOtherV1DocCategory(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasOtherOtherV1DocCategory fromValue(String input) {
    for (DataAccessSchemasOtherOtherV1DocCategory b : DataAccessSchemasOtherOtherV1DocCategory.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
