/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DataAccessSchemasInsurancePolicyInsurancePolicyV1PaymentInterval {
  MONATLICH("monatlich"),
  VIERTELJ_HRLICH("vierteljährlich"),
  HALBJ_HRLICH("halbjährlich"),
  J_HRLICH("jährlich");

  private String value;

  DataAccessSchemasInsurancePolicyInsurancePolicyV1PaymentInterval(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasInsurancePolicyInsurancePolicyV1PaymentInterval fromValue(String input) {
    for (DataAccessSchemasInsurancePolicyInsurancePolicyV1PaymentInterval b : DataAccessSchemasInsurancePolicyInsurancePolicyV1PaymentInterval.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
