/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DataAccessSchemasIdentityDocIdentityDocV1IdentityDocType {
  ID_CARD("id_card"),
  PASSPORT("passport"),
  DRIVERS_LICENSE("drivers_license");

  private String value;

  DataAccessSchemasIdentityDocIdentityDocV1IdentityDocType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasIdentityDocIdentityDocV1IdentityDocType fromValue(String input) {
    for (DataAccessSchemasIdentityDocIdentityDocV1IdentityDocType b : DataAccessSchemasIdentityDocIdentityDocV1IdentityDocType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
