/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Supported payment methods.      Note: &#x60;multiple_options&#x60; is deprecated.     
 */
public enum DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1PaymentMethod {
  MONEY_TRANSFER("money_transfer"),
  BANK_COLLECTION("bank_collection"),
  CASH("cash"),
  CARD("card"),
  DEBIT("debit"),
  AMAZON("amazon"),
  PAYPAL("paypal"),
  CREDIT_CARD("credit_card"),
  PREPAYMENT("prepayment"),
  MULTIPLE_OPTIONS("multiple_options"),
  OTHER("other");

  private String value;

  DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1PaymentMethod(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1PaymentMethod fromValue(String input) {
    for (DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1PaymentMethod b : DataAccessSchemasConstantsBaseExtractionsBaseExtractionsV1PaymentMethod.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
