/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DataAccessSchemasCorrespondenceCorrespondenceV1SenderCategory {
  LAWYER("lawyer"),
  EMPLOYER("employer"),
  EDUCATION("education"),
  SERVICE_PROVIDER("service_provider"),
  RETAIL("retail"),
  ENERGY("energy"),
  REAL_ESTATE("real_estate"),
  COMMUNICATION("communication"),
  MOBILITY("mobility"),
  INDIVIDUAL("individual"),
  ENTERTAINMENT("entertainment"),
  MISCELLANEOUS("miscellaneous"),
  PUBLIC_SECTOR("public_sector"),
  HEALTHCARE("healthcare"),
  FINANCE("finance");

  private String value;

  DataAccessSchemasCorrespondenceCorrespondenceV1SenderCategory(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasCorrespondenceCorrespondenceV1SenderCategory fromValue(String input) {
    for (DataAccessSchemasCorrespondenceCorrespondenceV1SenderCategory b : DataAccessSchemasCorrespondenceCorrespondenceV1SenderCategory.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
