/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DataAccessSchemasOtherOtherV1SenderCategory {
  ANWALT("anwalt"),
  BANK("bank"),
  DIENSTLEISTER("dienstleister"),
  EINZELHANDEL("einzelhandel"),
  ENERGIE("energie"),
  FINANZAMT("finanzamt"),
  FINANZDIENSTLEISTER("finanzdienstleister"),
  GENOSSENSCHAFT("genossenschaft"),
  GERICHT("gericht"),
  GEWERKSCHAFTEN("gewerkschaften"),
  IMMOBILIEN("immobilien"),
  INKASSO("inkasso"),
  KRANKENKASSE("krankenkasse"),
  NOTAR("notar"),
  OEFFENTLICHE_VERWALTUNG("oeffentliche_verwaltung"),
  STAATSANWALTSCHAFT("staatsanwaltschaft"),
  STEUERBERATER("steuerberater"),
  SONSTIGES("sonstiges");

  private String value;

  DataAccessSchemasOtherOtherV1SenderCategory(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasOtherOtherV1SenderCategory fromValue(String input) {
    for (DataAccessSchemasOtherOtherV1SenderCategory b : DataAccessSchemasOtherOtherV1SenderCategory.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
