/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum DataAccessSchemasDocDocV1Language {
  CS("cs"),
  DE("de"),
  EN("en"),
  FR("fr"),
  PL("pl"),
  ES("es"),
  NL("nl"),
  JA("ja"),
  XX("xx");

  private String value;

  DataAccessSchemasDocDocV1Language(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DataAccessSchemasDocDocV1Language fromValue(String input) {
    for (DataAccessSchemasDocDocV1Language b : DataAccessSchemasDocDocV1Language.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
