/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The type of the document.
 */
public enum DocType {
  ADDRESS_CHANGE("address_change"),
  ANONYMIZATION("anonymization"),
  APPROVAL_OF_COST_COVERAGE("approval_of_cost_coverage"),
  ARRETE("arrete"),
  BAILIFF_NOTIFICATIONS("bailiff_notifications"),
  BANK_STATEMENT("bank_statement"),
  BILLING_LETTER("billing_letter"),
  CMR_DOC("cmr_doc"),
  CREDIT_NOTE("credit_note"),
  CRANE("crane"),
  DAMAGE_NOTICE("damage_notice"),
  DEATH_CERTIFICATE("death_certificate"),
  DELIVERY_NOTE("delivery_note"),
  DELIVERY_NOTE_CONSTRUCTION("delivery_note_construction"),
  ENFORCEMENT_ORDER("enforcement_order"),
  ENROLLMENT_CERTIFICATE("enrollment_certificate"),
  ENVELOPE("envelope"),
  EXTENDED_IDENTITY_DOC("extended_identity_doc"),
  HOTEL_INVOICE("hotel_invoice"),
  IDENTITY_DOC("identity_doc"),
  INSURANCE_BUSINESS_TRANSACTION("insurance_business_transaction"),
  INSURANCE_DOC("insurance_doc"),
  INSURANCE_POLICY("insurance_policy"),
  INSURANCE_RESIGNATION("insurance_resignation"),
  INVOICE("invoice"),
  INVOICE_CONSTRUCTION("invoice_construction"),
  INVOICE_CRAFTSPERSON("invoice_craftsperson"),
  INVOICE_DMG("invoice_dmg"),
  INVOICE_NER_GROUPINGS_MIGRATION("invoice_ner_groupings_migration"),
  INVOICE_W_VEHICLE_INFO("invoice_w_vehicle_info"),
  INCOME_TAX_STATEMENT("income_tax_statement"),
  LEGAL_DOC("legal_doc"),
  LETTER("letter"),
  LOAN_AGREEMENT("loan_agreement"),
  ORDER_CONFIRMATION("order_confirmation"),
  OTHER("other"),
  PENSION_INFORMATION("pension_information"),
  PHYSICIAN_TRAINING_EVENT("physician_training_event"),
  PRIVATE_HEALTH_INSURANCE("private_health_insurance"),
  PREPAID_CREDITS_PAYOUT_FORM("prepaid_credits_payout_form"),
  PURCHASE_ORDER("purchase_order"),
  RECEIPT("receipt"),
  SALARY_STATEMENT("salary_statement"),
  SALES_ORDER("sales_order"),
  VEHICLE_EXPERT_REPORT("vehicle_expert_report"),
  VEHICLE_PURCHASE_CONTRACT("vehicle_purchase_contract"),
  VEHICLE_REGISTRATION("vehicle_registration"),
  WAGE_TAX_CERTIFICATE("wage_tax_certificate"),
  SPEEDING_FINE("speeding_fine"),
  DOCUWORLD_FORM("docuworld_form"),
  TAX_STATEMENT("tax_statement"),
  TIME_SHEET("time_sheet"),
  INVOICE_CZECH("invoice_czech"),
  DUMMY_TEXT_NER("dummy_text_ner"),
  CORRESPONDENCE("correspondence"),
  EXTENDED_ACCOUNTING_INFORMATION("extended_accounting_information"),
  EXPORT_ACCOMPANYING_DOCUMENT("export_accompanying_document"),
  INVOICE_SLOVAK("invoice_slovak"),
  RECEIPT_CZECH("receipt_czech"),
  CONSTRUCTION_FILE("construction_file"),
  INSURANCE_FF("insurance_ff"),
  RECEIPT_WITH_SUBJECT("receipt_with_subject"),
  RECEIPT_REWORKED("receipt_reworked"),
  VETERINARIAN_INVOICE("veterinarian_invoice"),
  INVOICE_WITH_SUBJECT("invoice_with_subject");

  private String value;

  DocType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DocType fromValue(String input) {
    for (DocType b : DocType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
