/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum ExtendedIdentityDocType {
  ID_CARD("id_card"),
  PASSPORT("passport"),
  DRIVERS_LICENSE("drivers_license"),
  BANK_STATEMENT("bank_statement"),
  TAX_CERTIFICATE("tax_certificate"),
  REGISTRATION_CERTIFICATE("registration_certificate"),
  OTHER("other");

  private String value;

  ExtendedIdentityDocType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ExtendedIdentityDocType fromValue(String input) {
    for (ExtendedIdentityDocType b : ExtendedIdentityDocType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
