/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
/**
* Filter by postprocessing status. One of \&quot;reviewed\&quot;, \&quot;rejected\&quot;, \&quot;toreview\&quot;, \&quot;manual\&quot;, \&quot;auto\&quot;, \&quot;pending\&quot;, \&quot;warning\&quot;, or \&quot;all\&quot; to not filter by postprocessing status.
*/
@JsonTypeInfo(
  use = JsonTypeInfo.Id.NAME,
  include = JsonTypeInfo.As.PROPERTY,
  property = "type")
@JsonSubTypes({
})
public interface PostprocessingStatus {

}
