/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum Role {
  ADMIN("admin"),
  RESELLER("reseller"),
  DEMO_CREATOR("demo_creator"),
  MANAGER("manager"),
  USER("user"),
  ANNOTATION_MANAGER("annotation_manager"),
  ANNOTATOR("annotator"),
  MACHINE_USER("machine_user"),
  SHARELINK_USER("sharelink_user"),
  DEMO("demo");

  private String value;

  Role(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Role fromValue(String input) {
    for (Role b : Role.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
