/*
 * Document Capturing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.axonivy.connector.idp.connector.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * An enumeration.
 */
public enum WorkflowCategory {
  PREBUILT("prebuilt"),
  EDITOR("editor"),
  CUSTOM_DOCUMENT_CLASSIFICATION("custom_document_classification"),
  FINE_TUNED_ENTITY_CLASSIFICATION("fine_tuned_entity_classification"),
  CUSTOM_EXTRACTION("custom_extraction");

  private String value;

  WorkflowCategory(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static WorkflowCategory fromValue(String input) {
    for (WorkflowCategory b : WorkflowCategory.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
